// Load Jenkins shared library
jenkinsBranch = 'CI-15481-sift-php'
sharedLib = library("shared-lib@${jenkinsBranch}")

def siftPhpWorkflow = sharedLib.com.sift.ci.SiftPhpWorkflow.new()
def ciUtil = sharedLib.com.sift.ci.CIUtil.new()
def stackdriver = sharedLib.com.sift.ci.StackDriverMetrics.new()

// Default GitHub status context for automatically triggered builds
def defaultStatusContext = 'Jenkins:auto'

// GitHub repo name
def repoName = 'sift-php'

pipeline {
    agent none
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
        disableRestartFromStage()
        parallelsAlwaysFailFast()
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '30', numToKeepStr: '')
        timeout(time: 1, unit: 'HOURS')
    }
    environment {
        GIT_BRANCH = "${env.CHANGE_BRANCH != null? env.CHANGE_BRANCH : env.BRANCH_NAME}"
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                    statusContext = defaultStatusContext
                    // Get the commit sha for the build
                    commitSha = ciUtil.commitHashForBuild()
                    ciUtil.updateGithubCommitStatus(repoName, statusContext, 'Started', 'pending', commitSha)
                }
            }
        }
        stage ('Build and Test Workflows') {
            steps {
                script {
                    def workflows = [:]

                    // Unit tests
                    def unitTestStages = [
                        'Tests - php 7.1':'7.1',
                        'Tests - php 7.2':'7.2',
                        'Tests - php 7.3':'7.3',
                        'Tests - php 7.4':'7.4'
                    ]

                    unitTestStages.each { stageName, phpVersion ->
                        workflows[stageName] = {
                            stage(stageName) {
                                ciUtil.updateGithubCommitStatus(repoName, stageName, 'Started', 'pending', commitSha)
                                try {
                                    siftPhpWorkflow.runSiftPhpTest("php-${phpVersion.replace('.', '-')}-pod-template.yaml", "php${phpVersion}-${BUILD_TAG}", phpVersion)
                                    ciUtil.updateGithubCommitStatus(repoName, stageName, 'SUCCESS', 'success', commitSha)
                                } catch (Exception e) {
                                    ciUtil.updateGithubCommitStatus(repoName, stageName, 'FAILURE', 'failure', commitSha)
                                    print("${stageName} failed")
                                    throw e
                                }
                            }
                        }
                    }

                    // Integration tests
                    def phpIntegrationTestsVersion = "7.4"
                    def integrationTestsStageName = "Integration Tests - php ${phpIntegrationTestsVersion}"
                    workflows[integrationTestsStageName] = {
                        stage(integrationTestsStageName) {
                            ciUtil.updateGithubCommitStatus(repoName, integrationTestsStageName, 'Started', 'pending', commitSha)
                            try {
                                siftPhpWorkflow.runSiftPhpIntegration("php-${phpIntegrationTestsVersion.replace('.','-')}-pod-template.yaml", "php${phpIntegrationTestsVersion}-${BUILD_TAG}", phpVersion)
                                ciUtil.updateGithubCommitStatus(repoName, integrationTestsStageName, 'SUCCESS', 'success', commitSha)
                            } catch (Exception e) {
                                ciUtil.updateGithubCommitStatus(repoName, integrationTestsStageName, 'FAILURE', 'failure', commitSha)
                                print("${integrationTestsStageName} failed")
                                throw e
                            }
                        }
                    }

                    parallel workflows
                }
            }
        }
    }
    post {
        success {
            script {
                ciUtil.updateGithubCommitStatus(repoName, statusContext, currentBuild.currentResult, 'success', commitSha)
            }
        }
        unsuccessful {
            script {
                ciUtil.updateGithubCommitStatus(repoName, statusContext, currentBuild.currentResult, 'failure', commitSha)
                ciUtil.notifySlack(repoName, commitSha)
            }
        }
        always {
            script {
                stackdriver.updatePipelineStatistics(this)
            }
        }
    }
}
