name: PHP Composer

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sift-php
    steps:
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1.27'
      - name: Validate composer.json and composer.lock
        run: |
          composer validate --strict
        working-directory: sift-php
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: siftPhpTest
        run: composer exec phpunit -v

  run-integration-tests-php74:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate composer.json and composer.lock
        run: composer install --prefer-dist --no-progress


