name: PHP Composer

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1.27'
      - name: Validate composer.json and composer.lock
        run: |
          sudo composer self-update
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-v1-{{ checksum "composer.lock" }}
          restore-keys: |
            composer-v1-
      - run: composer install --prefer-dist --no-progress
      - name: siftPhpTest
        run: composer exec phpunit -v

  run-integration-tests-php74:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate composer.json and composer.lock
        run: composer install --prefer-dist --no-progress


